objects/Map__c/Map__c.object-meta.xml
<CustomObject>
    <label>Map</label>
    <nameField>
        <label>Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Neighborhood__c/Neighborhood__c.object-meta.xml
<CustomObject>
    <label>Neighborhood</label>
    <nameField>
        <label>Neighborhood Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Neighborhoods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Seat__c/Seat__c.object-meta.xml
<CustomObject>
    <label>Seat</label>
    <nameField>
        <label>Seat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Seat__c/fields/Coordinates__c.field-meta.xml
<CustomField>
    <fullName>Coordinates__c</fullName>
    <label>Coordinates</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Seat__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Map__c</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Seat__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Neighborhood</label>
    <referenceTo>Neighborhood__c</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Seat__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
                <default>true</default>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Non Reservable</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Seat_Reservation__c/Seat_Reservation__c.object-meta.xml
<CustomObject>
    <label>Seat Reservation</label>
    <nameField>
        <label>Seat Reservation  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seat Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Seat_Reservation__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>Seat</label>
    <referenceTo>Seat__c</referenceTo>
    <relationshipLabel>Seat Reservations</relationshipLabel>
    <relationshipName>Seat_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Time_Reservation__c/Time_Reservation__c.object-meta.xml
<CustomObject>
    <label>Time Reservation</label>
    <nameField>
        <label>Meeting Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Reservation__c/fields/EndTime_Min__c.field-meta.xml
<CustomField>
    <fullName>EndTime_Min__c</fullName>
    <label>EndTime Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Time_Reservation__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>Seat</label>
    <referenceTo>Seat__c</referenceTo>
    <relationshipLabel>Time Reservations</relationshipLabel>
    <relationshipName>Time_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Time_Reservation__c/fields/StartTime_Min__c.field-meta.xml
<CustomField>
    <fullName>StartTime_Min__c</fullName>
    <label>StartTime Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/mySeatReservationsCtrlTest.cls
@isTest
public with sharing class mySeatReservationsCtrlTest {

    @TestSetup
    static void makeData(){
        TestHelper.makeData();
    }

    @isTest
    public static void mySeatReservationsCtrlTest() {
        List<Seat__c> seats =  [SELECT Id, Name, Coordinates__c, Neighborhood__c, Type__c, Floor__c FROM Seat__c WHERE Type__c='Daily'];
        List<Seat__c> hourlySeats =  [SELECT Id, Name, Coordinates__c, Type__c, Neighborhood__c, Floor__c FROM Seat__c WHERE Type__c='Hourly'];
        Date dt = Date.Today().toStartOfWeek().addDays(9);
        reservationWiz.TakeSeatMulti(seats[0].Name, String.valueOf(dt)+','+String.valueOf(dt), seats[0].Floor__c, seats[0].Type__c,'');
        reservationWiz.TakeSeatMulti(hourlySeats[0].Name,String.valueOf(dt)+','+String.valueOf(dt),hourlySeats[0].Floor__c, hourlySeats[0].Type__c, '09:00-10:00');
        List<SeatService.SeatResrvation> seatRes = mySeatReservationsCtrl.getMyReservations();
        mySeatReservationsCtrl.getMyTimeReservations();
        List<Seat_Reservation__c> sr = [SELECT Id FROM Seat_Reservation__c];
        List<Time_Reservation__c> tr = [SELECT Id, Seat__r.name, Date__c, Seat__r.Floor__r.name, Seat__r.Floor__c, StartTime_MIN__c, EndTime_MIN__c FROM Time_Reservation__c];
        SeatService.SeatTimeResrvation str = new SeatService.SeatTimeResrvation(tr[0]);
        mySeatReservationsCtrl.RemoveSeatResrvation(sr[0].Id);
        mySeatReservationsCtrl.RemoveSeatTimeResrvation(tr[0].Id);
        try{
            mySeatReservationsCtrl.RemoveSeatResrvation(sr[0].Id);
        }catch(Exception e){}
        try{
            mySeatReservationsCtrl.RemoveSeatTimeResrvation(tr[0].Id);
        }catch(Exception e){}
    }
}