objects/Map__c/Map__c.object-meta.xml
<CustomObject>
    <label>Map</label>
    <nameField>
        <label>Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Map__c/fields/Map_Image__c.field-meta.xml
<CustomField>
    <fullName>Map_Image__c</fullName>
    <inlineHelpText>Add a URL for the image of the map.
One option is uploading a static resource file as public and add the link here.</inlineHelpText>
    <label>Map Image</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

objects/Neighborhood__c/Neighborhood__c.object-meta.xml
<CustomObject>
    <label>Neighborhood</label>
    <nameField>
        <label>Neighborhood Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Neighborhoods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Seat__c/Seat__c.object-meta.xml
<CustomObject>
    <label>Seat</label>
    <nameField>
        <label>Seat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Seat__c/fields/Coordinates__c.field-meta.xml
<CustomField>
    <fullName>Coordinates__c</fullName>
    <label>Coordinates</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Seat__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Map__c</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Seat__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Neighborhood</label>
    <referenceTo>Neighborhood__c</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Seat__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
                <default>true</default>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Non Reservable</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Seat__c/fields/Worker__c.field-meta.xml
<CustomField>
    <fullName>Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Worker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Seats</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Seat_Reservation__c/Seat_Reservation__c.object-meta.xml
<CustomObject>
    <label>Seat Reservation</label>
    <nameField>
        <label>Seat Reservation  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seat Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Seat_Reservation__c/fields/Reservation_Date__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Date__c</fullName>
    <label>Reservation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Seat_Reservation__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>Seat</label>
    <referenceTo>Seat__c</referenceTo>
    <relationshipLabel>Seat Reservations</relationshipLabel>
    <relationshipName>Seat_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Seat_Reservation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Seat_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Seat_Reservation__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <externalId>true</externalId>
    <label>Week</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

classes/TestHelper.cls
public with sharing class TestHelper {


    public static Map__c returnFloorMap(String floorName){
        Map__c m  = new Map__c(Name = floorName, Map_Image__c=URL.getSalesforceBaseUrl().toExternalForm()+'maps/'+floorName);
        return m;
    }

    // public static Neighborhood_Coordinates__c returnNeighborhoodCoords(String ncName, Id mapId ){
    //     return new Neighborhood_Coordinates__c(Name = ncName, Map__c = mapId);
    // }

    public static Neighborhood__c returnNeighborhood(String nName ){
        return new Neighborhood__c(Name = nName);
    }

    public static Seat__c returnSeat(String Coordinates, String name, Id nId, Id mapId ){
        return new Seat__c(Coordinates__c = Coordinates, Name = name, Neighborhood__c = nId, Floor__c = mapId);
    }

    public static Seat_Reservation__c returnSeat(Date Reservation_Date, Id Worker, Id seatId){
        DateTime dt = DateTime.newInstance(Reservation_Date.year(),Reservation_Date.month(),Reservation_Date.day());
        return returnSeatDT(dt, Worker, seatId);
    }

    public static Seat_Reservation__c returnSeatDT(DateTime dt, Id Worker, Id seatId){
        return new Seat_Reservation__c(Reservation_Date__c = dt.Date(),	Week__c = dt.format('w'), User__c = Worker, Seat__c = seatId);
    }

    public static void makeData(){
        List<String> types = reservationWiz.getSeatType();

        List<Map__c> mapList = new List<Map__c>();
        for(Integer i =0; i<3; i++){
            mapList.add(returnFloorMap('Floor Map'+i));
        }
        insert mapList;


        List<Neighborhood__c> nList = new List<Neighborhood__c>();
        nList.add(returnNeighborhood('test1'));
        nList.add(returnNeighborhood('test2'));
        insert nList;

        List<Seat__c> seatList = new List<Seat__c>();
        Integer j =0;
        for(Neighborhood__c nc : nList){
            Id MapId = mapList[j].Id;
            for(Integer i =0; i<types.size(); i++){
                seatList.add(returnSeat( getCoords(i), nc.name+' Seat '+(i+1), nc.Id, MapId) );
                seatList[seatList.size()-1].Type__c = types[i];
                if(types[i].containsIgnoreCase('Permanent')){
                    seatList[seatList.size()-1].Worker__c = UserInfo.getUserId();
                }
            }
            j++;
        }
        insert seatList;
    }

    public static String getCoords(Integer i){
        return i==0?'0,0,10,0,10,10,10,0':'10,0,20,0,20,10,10,10';
    }
}